name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+*

jobs:

  create-release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout repository
        run: |
          if [ "$GITHUB_EVENT_NAME" = push ]; then
            exit
          fi
          tag=$(git tag --sort=-version:refname | head -n1)
          if [ -z "$tag" ]; then
            echo 'repo has no tags.' >&2
            exit 1
          fi
          echo "checking out to the latest tag ($tag)"
          git checkout "$tag"

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          mkdir build
          cd build
          for arch in amd64 arm64; do
            go build -v -trimpath -ldflags='-s -w -buildid=' \
              -o="netexp-linux-$arch" ./cmd/netexp
          done
          sha256sum -- * > sha256sums.txt

      - name: Create release
        run: |
          tag=$(git describe --tags --exact-match)
          gh release create --generate-notes --title="$tag" -- "$tag" build/*
