name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+*

jobs:

  create-release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Switch to the latest tag if triggered via workflow_dispatch
        run: |
          if [ "$GITHUB_EVENT_NAME" = push ]; then
            exit
          fi
          echo 'finding the latest tag'
          latest_tag=$(git tag --sort=-version:refname | head -n1)
          if [ -z "$latest_tag" ]; then
            echo 'repo has no tags' >&2
            exit 1
          fi
          echo "switching to the latest tag ($latest_tag)"
          git checkout "$latest_tag"

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Build reproducibly
        run: |

          umask 0022
          mkdir tarballs

          tag=$(git describe --tags --exact-match)
          commit_time=$(git log -1 --pretty=%ct)
          export SOURCE_DATE_EPOCH=$commit_time

          for arch in amd64 arm64; do

            build=netexp-linux-$arch
            echo "building $build"
            mkdir "$build"

            GOOS=linux GOARCH=$arch go build \
              --trimpath \
              --buildvcs=false \
              --ldflags="-s -w --buildid= -X=main.version='$tag'" \
              -o="$build/netexp" \
              ./cmd/netexp

            chmod 755 -- "$build/netexp"

            tar \
              --create \
              --format=ustar \
              --sort=name \
              --owner=0 \
              --group=0 \
              --numeric-owner \
              --mtime="@${SOURCE_DATE_EPOCH:?}" \
              --use-compress-program='gzip --no-name' \
              --file="tarballs/$build.tar.gz" \
              -- "$build"

          done

          cd tarballs
          sha256sum -- * > sha256sums.txt

      - name: Create release
        run: |
          tag=$(git describe --tags --exact-match)
          gh release create --generate-notes --title="$tag" -- "$tag" tarballs/*
        env:
          GH_TOKEN: ${{ github.token }}
